- name: Create Azure VM
  hosts: localhost
  connection: local
  tasks:
  - name: Create Resource Group
    azure_rm_resourcegroup
      name: "ansiblerg"
      location: southcentralus
      state: present
